name: CI

on:
  pull_request:
    branches: ["dev", "main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install modules
        run: npm install
      - name: Lint
        run: npm run lint
      - name: Type check / Build
        run: npm run build
      - name: Test
        run: npm run test --if-present